<?php
$lang["openai_gpt_title"]                   = "OpenAI integration";
$lang["openai_gpt_intro"]                   = "Adds metadata generated by passing existing data or a resource preview image to the OpenAI API with a customisable prompt. Refer to the <a href='https://platform.openai.com/docs/introduction' target='_blank'>OpenAI documentation</a> for more detailed information.";
$lang["property-openai_gpt_prompt"]         = "GPT Prompt";
$lang["property-openai_gpt_input_field"]    = "GPT Input";
$lang["openai_gpt_api_key"]                 = "OpenAI API key. Get your API key from <a href='https://openai.com/api' target='_blank' >https://openai.com/api</a>";
$lang["openai_gpt_model"]                   = "Name of API model to use (e.g. 'gpt-4o')";
$lang["openai_gpt_temperature"]             = "Sampling temperature between 0 and 1 (higher values means the model will take more risks)";
$lang["openai_gpt_max_tokens"]              = "Max tokens";
$lang["openai_gpt_advanced"]                = "WARNING - This section is for testing purposes only and should not be changed on live systems. Changing any of the plugin options here will affect the behaviour of all the metadata fields that have been configured. Alter with caution!";
$lang["openai_gpt_system_message"]          = "Initial system message text. Placeholders %%IN_TYPE%% and %%OUT_TYPE%% will be replaced by 'text' or 'json' depending on the source/target field types";

$lang["openai_gpt_model_override"]          = "The model has been locked in global configuration to: [model]";

$lang["openai_gpt_processing_multiple_resources"] = "Multiple resources";
$lang["openai_gpt_processing_resource"] = "Resource [resource]";
$lang["openai_gpt_processing_field"] = "AI metadata generation for field '[field]'";

$lang["property-gpt_source"]="GPT Source";

$lang["openai_gpt_language"]              = "Output language";
$lang["openai_gpt_language_user"]         = "The language of the current user";
$lang["openai_gpt_overwrite_data"]        = "Overwrite existing data in configured fields?";

$lang["page-title_openai_gpt_setup"]      = "Setup OpenAI GPT Plugin";

$lang["openai_gpt"] = "OpenAI GPT";
$lang["openai_gpt_process_existing"] = "Process existing GPT fields";
$lang["openai_gpt_process_existing_field_ref"] = "AI Field";
$lang["openai_gpt_process_existing_overwrite"] = "Overwrite";
$lang["openai_gpt_process_existing_field_ref_help"] = "This is the target field to be updated.";
$lang["openai_gpt_process_existing_collection_refs_help"] = "Setting this option will mean only resources in the listed collections will be processed. If no collections are specified then ALL suitable resources will be processed. Collections can be specified using a comma-separated list as well as ranges e.g 100,105,110-115";
$lang["openai_gpt_process_existing_overwrite_help"] = "Setting this option will mean any existing data in the target field will be overwritten. Please note that if overwrite is enabled and the input field contains no data then the target field will be cleared.";